### ISSUE TITLE
Content negotiation? 

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#104]
Does this work as expected? If I enter the URI of an ontology I was expecting to get to the documentation page, but I end up in the github repository page instead.

**Comment by keski** [comment]
This is related to our namespace change. Right now `https://w3id.org/CEON/ontology-network/something` redirects to `https://liusemweb.github.io/CEON/something/`. A pull request is pending at w3id.org which will update this. Let's keep this issue open until the pull request has been merged.

**Comment by keski** [comment]
The [pull request](https://github.com/perma-id/w3id.org/pull/3216) has now been merged. See `tests/test_redirects.py` for a list of examples.
