### ISSUE TITLE
Instances in the documentation?

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#107]
Is it possible to show the instances of a class as a list (similar to how subclasses are shown now) in the documentation? Some of our concepts contains a set of instances, that constitute a list of known categories, e.g. the set of typical roles involved in a CVN or in relation to a resource in the actor module. It would be nice if these could be visible in the documentation page.

**Comment by keski** [comment]
This has now been implemented in our fork of pyLODE
