### ISSUE TITLE
cvn module report from evaluation

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#179]
# Report from FOOPS!
- [x] ~Inconsistent ontology IDs (error due to versioned ontology URI, ignore this)~
- [x] Minimum metadata missing (license)
- [x] ~Prefix not found in prefix.cc nor LOV registries (ontology not yet released, ignore this)~
- [x] ~Ontology not found in LOV registries (ontology not yet released, ignore this)~
- [x] ~Metadata not accessible in LOV registries (ontology not yet released, ignore this)~
- [x] OM2: Missing parts of recommended metadata (creation date, citation (?))
- [x] OM3: Missing detailed metadata (doi, publisher, logo, status, source, issued date) (not all are applicable)
- [x] Documentation label missing for 3 terms
- [x] Documentation definitions (`rdfs:comment` or `skos:definition`) missing for 2 terms
- [x] License is not resolvable
- [x] Basic provenance metadata missing (creation date)
- [x] ~Detailed provenance metadata missing (issued, publisher) (ontology not yet released, ignore this)~

# Report from OOPS!
- [x] Unconnected ontology elements (`Process`)
- [x] Missing annotations (see above)
- [x] ~Missing disjointness (ignore this)~
- [ ] Missing domain and range for properties (fix where applicable)
- [x] ~Inverse relationships not explicitly declared (ignore this)~
- [x] Ambiguous namespace (verify that ontology namespace is defined)

# SPARQL support for CQs
- CVN-1: Supported
- CVN-6: Partial support
- CVN-Process-1: Supported
- CVN-Process-6: Supported
- CVN-VP-1: Supported
- CVN-VP-3: Not covered
- CVN-Type-3: Partial support
- C0-1: Supported

**Comment by huanyu-li** [comment]
We have the latest evaluation report in the 2nd evaluation in terms of OOPS! and FOOPS! checking and SPARQL verification.
