### ISSUE TITLE
product module report from evaluation

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#181]
# Report from FOOPS!
- [x] Version IRI does not resolve
- [x] ~Inconsistent ontology IDs (error due to versioned ontology URI, ignore this)~
- [x] ~Prefix not found in prefix.cc nor LOV registries (ontology not yet released, ignore this)~
- [x] ~Ontology not found in LOV registries (ontology not yet released, ignore this)~
- [x] ~Metadata not accessible in LOV registries (ontology not yet released, ignore this)~
- [x] OM2: Missing parts of recommended metadata (citation (?))
- [x] OM3: Missing detailed metadata (doi, publisher, logo, status, source, issued date) (not all are applicable)
- [x] Documentation labels missing for 1 ontology term (`hasComposition`).
- [x] License is not resolvable
- [x] ~Detailed provenance metadata missing (issued, publisher) (ontology not yet released, ignore this)~

# Report from OOPS!
- [x] Unconnected ontology elements (`Resource`)
- [x] Missing domain or range in properties (`batchOfProduct`)
- [x] Missing annotations (see above)
- [x] ~Missing disjointness (ignore this)~
- [x] ~Inverse relationships not explicitly declared (ignore this)~
- [x] Defining multiple domains or ranges in properties (`hasComposition^)
- [x] Ambiguous namespace (verify that ontology namespace is defined)

# SPARQL support for CQs (for v. 0.1)
- CVN-Resource-2: Supported
- CVN-ResourceType-4: Supported
- C11-2: Partial support
- C12-1: Partial support
- C13-3: Partial support
- E2-1: Supported
- T8-3: Supported

**Comment by keski** [comment]
The domain for `hasComposition` was defined as `Product and PhysicalObject` whereas the associated comment made it clear that `Product or PhysicalObject` was intended. Can someone verify this? @evabl444 @huanyu-li

**Comment by evabl444** [comment]
Looks good
