### ISSUE TITLE
property for representing product model components

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#222]
We need a way of representing product model components, i.e., we need an abstract version of `ProductObject`'s `hasProductComponent` for `Product`. This should be added to the `product` module.

*Did we have naming convention for the abstract/concrete components?*

**Comment by keski** [comment]
Looking through the `product` module again I believe we may actually cover this as part using `hasComposition` and `Composition`. Example:
```turtle
<SomeShoeModel> a product:Product ;
    product:hasComposition [
        a product:ProductComposition ;
        product:associatedWithProductModel <SomeLaceType> ;
        product:compositionQuantity 1
    ] .
<SomeLaceType> a product:Product .
```
The issue is then instead about including a shortcut for linking to product models to product components.

Suggestion:
- Change domain and range of `product:hasProductComponent` to include also `product:Product`, or
- Split the `product:hasProductComponent` into two properties (`product:hasProductComponent` with range `Product` and `product:hasProductObjectComponent` with range `ProductObject`)

I prefer that latter due to the clear distinction between abstract and concrete products. Thoughts?

@evabl444

**Comment by evabl444** [comment]
Let's see if I get this... so you say that we have the Composition class, which is a reification of the composition relation, both for the item level and the model level? And then you suggest to have two separate "shortcuts", one for models and one for items?

But for the reification, is there a corresponding property to "product:associatedWithProductModel" for the case when it is a ProductObject that has a composition, and which should be related to components that are ProductObjects and not models?

Otherwise I also agree with the second bullet point. (But I did not have time to check the actual file today.)

**Comment by huanyu-li** [comment]
I think currently, at the concrete project object level, although we have physical object is also domain of hasComposition, we don't have some property like "product:associatedWithProductModel" to connect objects' composition to product model level.

I also agree with the second bullet point. As I understand, in such way, we kinda have two paralleled ways for both the product model level and object level. But then my concern is whether we need to have "Composition" at the model and object levels?

**Comment by keski** [comment]
`But then my concern is whether we need to have "Composition" at the model and object levels?` That is a good question... Not sure.

Maybe have:
- `ProductComposition` with `associatedWithProduct` (abstract)
- Direct link `product:hasProductComponent` (abstract)
- `ProductObjectComposition` with `associatedWithProductObject` (specific object)
- Direct link `product:hasProductObjectComponent` (specific object)

**Comment by huanyu-li** [comment]
> Or do we want to keep `associatedWithProductModel`? Any further thoughts on this? @evabl444 @huanyu-li

Do you mean have another property like `associatedWithProductObject` for ProductObjectComposition?
