### ISSUE TITLE
properties for representing location information

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#223]
We need a way to represent more specific location information. Suggested properties include:
- `countryOfManufacture`
- `countryOfOrigin`
- `countryOfAssembly`

Potentially, we should also consider location information related to the actual address/factory in which a product was manufactured or assembled. E.g.:
- `locationOfManufacture`
- `locationOfAssembly`

**Comment by keski** [comment]
Proposed solution is to extend the provenance module with a general notion of the suggested properties. That is, properties added as subproperties of `prov:atLocation` with domain `resourceODP:Resource`:

```turtle
:countryOfAssembly rdf:type owl:ObjectProperty ;
                   rdfs:subPropertyOf <http://www.w3.org/ns/prov#atLocation> ;
                   rdfs:domain resourceODP:Resource ;
                   rdfs:comment "Used to represent the country of assembly of a resource" ;
                   rdfs:label "Country of assembly" .

:countryOfManufacture rdf:type owl:ObjectProperty ;
                      rdfs:subPropertyOf <http://www.w3.org/ns/prov#atLocation> ;
                      rdfs:domain resourceODP:Resource ;
                      rdfs:comment "Used to represent the country of manufacture of a resource" ;
                      rdfs:label "Country of manufacture" .

:countryOfOrigin rdf:type owl:ObjectProperty ;
                 rdfs:subPropertyOf <http://www.w3.org/ns/prov#atLocation> ;
                 rdfs:domain resourceODP:Resource ;
                 rdfs:comment "Used to represent the country of origin of a resource" ;
                 rdfs:label "Country of origin" .

:locationOfAssembly rdf:type owl:ObjectProperty ;
                    rdfs:subPropertyOf <http://www.w3.org/ns/prov#atLocation> ;
                    rdfs:domain resourceODP:Resource ;
                    rdfs:comment "Used to represent the location where a resource was assembled" ;
                    rdfs:label "Location of assembly" .

:locationOfManufacture rdf:type owl:ObjectProperty ;
                       rdfs:subPropertyOf <http://www.w3.org/ns/prov#atLocation> ;
                       rdfs:domain resourceODP:Resource ;
                       rdfs:comment "Used to represent the location where a resource was manufactured" ;
                       rdfs:label "Location of manufacture" .
```

**Comment by evabl444** [comment]
Ok, makes sense, but these are then also shortcuts basically, actually referring to the location of the "assembly event/process" or "manfacturing event/process" that created them, right? We have to think a bit if there is a way to actually infer these shortcuts, or if this is maybe a case where the VSE transformation patterns could come into play?

And I would also like to say that the :countryOfAssembly should be a subproperty of the :locationOfAssembly, since a country is also a location, but a more specific one. Agree? 

Finally, this indicates that we should actually promote the provenance module to the core modules. But to do that I think we need to go through it properly and see if that means taking all of it, or just some core parts like this.

**Comment by keski** [comment]
> And I would also like to say that the :countryOfAssembly should be a subproperty of the :locationOfAssembly, since a country is also a location, but a more specific one. Agree?

I agree.

> Finally, this indicates that we should actually promote the provenance module to the core modules. But to do that I think we need to go through it properly and see if that means taking all of it, or just some core parts like this.

Perhaps we can just skip `prov:atLocation` for now and just add the properties to e.g. the `resource` or product module?

**Comment by keski** [comment]
@evabl444 @huanyu-li

**Comment by keski** [comment]
For now, I've added the location properties as datatype properties, but we should think more about how to represent location information (see also possibly related issue #228).
