### ISSUE TITLE
represent time and location for ProcessExecution

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#228]
There needs to be some way of representing time and location for `ProcessExecution`. E.g.
- add `occursAtTime` (with range temporal entity?)
- add `occursAtLocation` (i.e., equivalent to the abstract notion of `occursInLocation` for `Transformation`)

**Comment by huanyu-li** [comment]
For temporal entity, perhaps we can use OWL-Time (http://www.w3.org/2006/time#2016)?

**Comment by huanyu-li** [comment]
For Location, perhaps we can just simply create a concept Location and some data properties like hasCountry, hasCity?

**Comment by keski** [comment]
For now, `occursAtLocation` is left without a range, but we should probably consider adding a `Location` type. `occursAtTime` has been made into a datatype property with `xsd:dateTime` as range. We should discuss whether to extend this to use e.g. OWL-Time.
