### ISSUE TITLE
certificate information

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#230]
Add a property to represents certificates. E.g.:
- `hasCertificate` in one of the core modules (object property without range?)

Certificate is already mentioned in `construction` and maybe somewhere else as well.

**Comment by keski** [comment]
Added `hasCertificate` as an object property to the `product` module (version 0.3):
```turtle
:hasCertificate rdf:type owl:ObjectProperty ;
                rdfs:domain [ rdf:type owl:Class ;
                              owl:unionOf ( :Product
                                            :ProductObject
                                          )
                            ] ;
                rdfs:comment "hasCertifcate is used to link a product or product object to a certificate." ;
                rdfs:label "has certificate" .
```

The corresponding property removed from `construction`.

**Comment by evabl444** [comment]
Ok, sounds good as solution for now. Then later on we also need this for both processes and organisations as well. 

Btw there is a typo in the comment. And maybe I would suggest to phrase it "hasCertificate is used to link a product or product object to a certification that that product has, e.g. REACH or similar standard."
