### ISSUE TITLE
Double property for hasDismantlingCost, both in CEON quantity and construction ontology

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#244]

**Comment by huanyu-li** [comment]
Keep the one in CEON quantity, in addition, add labels and comments for `hasMarketValue`, `hasRefurbishmentCost`, `hasTestingCost` and `hasTransportCost`.

**Comment by huanyu-li** [comment]
Either `quantity` in core or not

**Comment by huanyu-li** [comment]
`quantity` module is put into core.
