### ISSUE TITLE
Breakdown of a batch of resources

### ISSUE THREAD

**Issue by elsdvlee** [LiUSemWeb/CEON#246]
A batch (e.g. Nortec floor items used in a specific room) can consists of items that are modelled by a certain product model (e.g.  Nortec). A product model can have product components. 
In the construction demo we want to sell or recycle the tiles of the batch and the pedestals (components of the batch Nortec floor items used in a specific room) as two separate batches. How do you express that a batch has 'subbatches'? In the demo I temporarily used also http://w3id.org/CEON/ontology/product/hasProductComponent, but that is not correct.

**Comment by huanyu-li** [comment]
refactor `hasBatch` to include `BatchOfObjects` as domain so that a batch can contain other batches.
