### ISSUE TITLE
ReverseProcessType

### ISSUE THREAD

**Issue by elsdvlee** [LiUSemWeb/CEON#247]
In the textile demo we connected the assembly method to the process (step) with http://w3id.org/CEON/ontology/processODP/hasProcessType: 

> ex:01_upper_part a ceon-process:AssemblingProcess;
> 	       ceon-processODP:hasInput ex:textile_A, ex:textile_B, ex:Resortec;
> 	       ceon-processODP:hasOutput ex:upper_part;
> 	       ceon-processODP:nextProcess ex:02_addsole;
> 	       ceon-processODP:hasProcessType ex:stiched_with_Resortec_thermo-dissolvable_stitch.

How to you express the disassemblyMethod? 
In the demo I temporarily used  ex:hasReverseProcessType. 

> ex:01_upper_part a ceon-process:AssemblingProcess;
> 	       ceon-processODP:hasInput ex:textile_A, ex:textile_B, ex:Resortec;
> 	       ceon-processODP:hasOutput ex:upper_part;
> 	       ceon-processODP:nextProcess ex:02_addsole;
> 	       ceon-processODP:hasProcessType ex:stiched_with_Resortec_thermo-dissolvable_stitch;
>             ex:hasReverseProcessType ex:heat_separation.

However, it might be possible to just inverse the complete process description 
> ex:01_upper_part a ceon-process:DissassemblingProcess;
> 	       ceon-processODP:hasInput ex:upper_part;
> 	       ceon-processODP:hasOutput ex:textile_A, ex:textile_B;
> 	       ceon-processODP:hasProcessType ex:heat_separation.

Still, I would think that you want be able to express that one process is the reverse of another process. 
Please advise, so I can update the textile demo.

**Comment by huanyu-li** [comment]
I will add DissassemblingProcess in the Process module.
