### ISSUE TITLE
wrong URIs and namespaces

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#45]
There are some wrong and outdated namespaces in some of the ontology files:

acctor.ttl
- http://w3id.org/CEON/ontology-network/cvn/CVN
- http://w3id.org/CEON/ontology-network/cvn/Collaboration
- http://w3id.org/CEON/ontology/actor//[...] (double slash)

actorODP.ttl
- http://w3id.org/CEON/ontology-network/cvn/Collaboration
- http://w3id.org/CEON/ontology-network/process/Process
- http://w3id.org/CEON/ontology-network/resource/Resource
- http://w3id.org/CEON/ontology/actorODP//[...] (double slash)

process.ttl
- http://w3id.org/CEON/ontology-network/Process# 
- http://w3id.org/CEON/ontology-network/Core#[...]

**Comment by keski** [comment]
@huanyu-li @evabl444

**Comment by huanyu-li** [comment]
Fixed now!
