### ISSUE TITLE
Extend the annotations picked up in documentation generation

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#58]
Can we add more annotation properties to be picked up when generating a module's documentation? For instance I would like to also store the CQs solved by the module in an annotation of the module itself.

**Comment by keski** [comment]
The easiest will probably be to fork the pyLODE repo and modify the following file(s):
- `rdf_elements.py`: Add corresponding property to the `ONT_PROPS`
- ...
Then update CEON to use this fork instead.

I'll check this out in more detail and get back with some more details.
