### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by gertjandemulder** [LiUSemWeb/CEON#96]
Hi all, I reviewed the repository (state at commit: fd1e8506634795a2fe8790477f5681303900033d) and have some (small) remarks.

## Setup

I'm missing an instruction to run/serve/host the generated documentation.
Suggestion: 

```bash
python -m “http.server” -d ./docs 
# navigate to http://localhost:8000/
```

## ActorODP

Participation
- Typo “har participating actor”, see https://github.com/LiUSemWeb/CEON/blob/develop/ontology/modules/actorODP/0.1/actorODP.ttl#L87

Role
- Typo “specfic”, see https://github.com/LiUSemWeb/CEON/blob/develop/ontology/modules/actorODP/0.1/actorODP.ttl#L213 

## ResourceODP

This is a small & concise module. LGTM.

## ProcessODP

I couldn't find ProcessODP on the index page.

## Actor

- In general, there’s no description about the classes, which makes it harder to review.

- The specialized Actor module contains more specializations of the Resource class than the Actor classes – perhaps this should be refactored to a specialized Resource module?
- Typo "updator". Replace with updater? https://github.com/LiUSemWeb/CEON/blob/develop/ontology/modules/actor/0.1/actor.ttl#L460

## Material

Concise & comprehensible module. LGTM.

## Product

Although the description of Product states that it is a thing that grows naturally or is produced by some kind or Process, there is no link to a Process (or subclass thereof). 
Perhaps this will be taken care of in the additional overarching module that will be introduced?

## Process

A concise module.

Although the subclasses of Processes are self-explaining, it would be nice to add a description describing which Actors and Products can be involved with them.

**Comment by keski** [comment]
Instructions on how to run/serve/host the generated documentation now included in the README

**Comment by evabl444** [comment]
I will take care of the refactoring needed for the remaining issues, I have a small list of things to move between modules + some missing relations.
