### ISSUE TITLE
Review #1b (high-level)

### ISSUE THREAD

**Issue by gertjandemulder** [LiUSemWeb/CEON#97]
Additionally, 

I would clarify in the repository not only the technical documentation, but also documentation on the method:

- [ ] Link to the ontology design method
- [ ] Link to the alignment between the devised ontology and the use case requirements that lead to specific classes/attributes/constraints. This also gives a hint at the completeness of the ontology with respect to the requirements.

**Comment by evabl444** [comment]
Thanks for the feedback! 
For the design method we have a summary and introduction of this in our pdf version of the deliverable, we will copy parts of this to the repository as well - @keski could you look at this? (See the overleaf document for the text.)
For the link to the requirements, this was also in the plan, just not implemented yet. @keski - you added the opportunity to annotate with covered requirements and get it picked up in the documentation, right? Can each person who created a module then please include such annotation, listing the requirements (just numbers from D3.1, not necessarily the whole CQs if there are many) in the modules they created? @huanyu-li
