### ISSUE TITLE
Include location of resources and actors

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#98]
WE should include the location of things, by referring to WGS84 (W3C standard vocab) and GeoSPARQL standard. This should be included through at least one property in both the actor module (or ODP?) and the resources module (or ODP?)

**Comment by huanyu-li** [comment]
To check:
http://www.w3.org/2003/01/geo/wgs84_pos#lat
http://www.w3.org/2003/01/geo/wgs84_pos#long

**Comment by huanyu-li** [comment]
Include more detailed for instance country, city

**Comment by huanyu-li** [comment]
more data properties were added into location module.
